name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          tags: true

      - name: Get the version
        id: get_version
        run: echo "::set-output name=VERSION::$(cat VERSION)"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git show-ref --tags | grep -q "^${{ steps.get_version.outputs.VERSION }}"; then
            echo "Tag already exists."
            echo "::set-output name=TAG_EXISTS::true"
          else
            echo "Tag does not exist."
            echo "::set-output name=TAG_EXISTS::false"
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: steps.check_tag.outputs.TAG_EXISTS == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.G_SECRET }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
