name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get the version
      id: get_version
      run: echo "::set-output name=VERSION::$(cat VERSION)"

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag anrbn/gator:${{ steps.get_version.outputs.VERSION }}
        docker push anrbn/gator:${{ steps.get_version.outputs.VERSION }}
